#!/usr/bin/env bash
# Help for production scripts
# Usage: ./help.sh [script]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

show_help() {
    local script="$1"

    case "$script" in
        deploy)
            echo "🚀 Deployment Script"
            echo "========================="
            echo ""
            echo "Usage: ./deploy.sh [options]"
            echo ""
            echo "Options:"
            echo "  --backup          Create backup before deployment"
            echo "  --migrate         Apply database migrations"
            echo "  --service=SERVICE Deploy only a specific service"
            echo ""
            echo "Examples:"
            echo "  ./deploy.sh"
            echo "  ./deploy.sh --backup"
            echo "  ./deploy.sh --backup --migrate"
            echo "  ./deploy.sh --service=calendar-web"
            ;;
        backup)
            echo "💾 Backup Script"
            echo "======================="
            echo ""
            echo "Usage: ./backup.sh [options]"
            echo ""
            echo "Options:"
            echo "  --list                List available backups"
            echo "  --restore=FILE        Restore from backup"
            echo ""
            echo "Examples:"
            echo "  ./backup.sh"
            echo "  ./backup.sh --list"
            echo "  ./backup.sh --restore=~/backups/db-backup-20251213-120000.sql.gz"
            ;;
        monitor)
            echo "📊 Monitoring Script"
            echo "======================"
            echo ""
            echo "Usage: ./monitor.sh [options]"
            echo ""
            echo "Options:"
            echo "  --all      Show all information"
            echo "  --health   Show health status"
            echo "  --stats    Show resource statistics"
            echo "  --logs     Show recent logs"
            echo "  --errors   Show recent errors"
            echo ""
            echo "Examples:"
            echo "  ./monitor.sh --all"
            echo "  ./monitor.sh --health"
            echo "  ./monitor.sh --stats"
            ;;
        health-check)
            echo "🏥 Health Check Script"
            echo "==================================="
            echo ""
            echo "Usage: ./health-check.sh [options]"
            echo ""
            echo "Options:"
            echo "  --verbose  Show check details"
            echo ""
            echo "Examples:"
            echo "  ./health-check.sh"
            echo "  ./health-check.sh --verbose"
            ;;
        cleanup)
            echo "🧹 Cleanup Script"
            echo "======================"
            echo ""
            echo "Usage: ./cleanup.sh [options]"
            echo ""
            echo "Options:"
            echo "  --all          Clean images, cache and logs"
            echo "  --images       Clean unused images"
            echo "  --volumes      Clean unused volumes (⚠️ destructive)"
            echo "  --logs         Clean logs"
            echo "  --system       Complete Docker system cleanup (⚠️ very destructive)"
            echo "  --build-cache  Clean build cache"
            echo ""
            echo "Examples:"
            echo "  ./cleanup.sh --all"
            echo "  ./cleanup.sh --images"
            echo "  ./cleanup.sh --build-cache"
            ;;
        quick-commands)
            echo "⚡ Quick Commands"
            echo "===================="
            echo ""
            echo "Usage: ./quick-commands.sh [command] [service]"
            echo ""
            echo "Commands:"
            echo "  status, ps              Service status"
            echo "  logs [service]          Real-time logs"
            echo "  restart [service]       Restart"
            echo "  stop [service]          Stop"
            echo "  start [service]         Start"
            echo "  shell-db                PostgreSQL shell"
            echo "  shell-server            Backend shell"
            echo "  shell-web               Frontend shell"
            echo "  stats                   Statistics"
            echo "  top                     Processes"
            echo "  env                     Configuration"
            echo ""
            echo "Examples:"
            echo "  ./quick-commands.sh status"
            echo "  ./quick-commands.sh logs server"
            echo "  ./quick-commands.sh restart web"
            ;;
        rollback)
            echo "🔄 Rollback Script"
            echo "====================="
            echo ""
            echo "Usage: ./rollback.sh [options]"
            echo ""
            echo "Options:"
            echo "  --commit=HASH   Specific commit (otherwise prompts)"
            echo "  --no-backup     Don't create backup before rollback"
            echo "  --no-db         Don't restore database"
            echo ""
            echo "Examples:"
            echo "  ./rollback.sh"
            echo "  ./rollback.sh --commit=abc123"
            echo "  ./rollback.sh --commit=HEAD~1 --no-backup"
            ;;
        verify-backup)
            echo "🔍 Backup Verification"
            echo "============================="
            echo ""
            echo "Usage: ./verify-backup.sh [FILE]"
            echo ""
            echo "If FILE is provided, verifies that specific file."
            echo "Otherwise, verifies all backups in BACKUP_DIR."
            echo ""
            echo "Examples:"
            echo "  ./verify-backup.sh"
            echo "  ./verify-backup.sh ~/backups/db-backup-20251213.sql.gz"
            ;;
        security-audit)
            echo "🔒 Security Audit"
            echo "==================="
            echo ""
            echo "Usage: ./security-audit.sh [options]"
            echo ""
            echo "Options:"
            echo "  --verbose       Show check details"
            echo ""
            echo "Checks:"
            echo "  - SSL certificates"
            echo "  - Security headers"
            echo "  - Environment variables"
            echo "  - Docker configuration"
            echo "  - Port exposure"
            echo ""
            echo "Examples:"
            echo "  ./security-audit.sh"
            echo "  ./security-audit.sh --verbose"
            ;;
        report)
            echo "📊 Status Report"
            echo "================"
            echo ""
            echo "Usage: ./report.sh [options]"
            echo ""
            echo "Options:"
            echo "  --format=text|json  Report format (default: text)"
            echo "  --output=FILE       Output file (default: stdout)"
            echo ""
            echo "Examples:"
            echo "  ./report.sh"
            echo "  ./report.sh --format=json --output=report.json"
            echo "  ./report.sh --format=text --output=report.txt"
            ;;
        install)
            echo "📦 Installation Script"
            echo "========================"
            echo ""
            echo "Usage: ./install.sh user@server"
            echo ""
            echo "Installs all production scripts on a remote server."
            echo ""
            echo "Examples:"
            echo "  ./install.sh root@185.158.132.190"
            echo "  ./install.sh user@example.com"
            echo ""
            echo "The script copies:"
            echo "  - All .sh scripts to ~/appstandard/scripts/production/"
            echo "  - PRODUCTION_COMMANDS.md to ~/appstandard/"
            ;;
        *)
            echo "📚 Help - AppStandard Production Scripts"
            echo "=========================================="
            echo ""
            echo "Available scripts:"
            echo ""
            echo "  🚀 deploy.sh          - Deploy application"
            echo "  💾 backup.sh          - Backup and restore"
            echo "  🔄 rollback.sh        - Rollback to previous version"
            echo "  📊 monitor.sh         - Monitoring and statistics"
            echo "  🏥 health-check.sh    - Health verification"
            echo "  🔒 security-audit.sh  - Security audit"
            echo "  🔍 verify-backup.sh   - Backup integrity verification"
            echo "  📊 report.sh          - Status report (text/JSON)"
            echo "  🧹 cleanup.sh         - Docker cleanup"
            echo "  ⚡ quick-commands.sh  - Quick commands"
            echo "  📦 install.sh         - Install on remote server"
            echo "  ❓ help.sh            - This help"
            echo ""
            echo "Usage:"
            echo "  ./help.sh [script]    - Help for specific script"
            echo ""
            echo "Examples:"
            echo "  ./help.sh deploy"
            echo "  ./help.sh backup"
            echo "  ./help.sh rollback"
            echo ""
            echo "For more information, see:"
            echo "  ~/appstandard/PRODUCTION_COMMANDS.md"
            echo "  scripts/production/README.md"
            ;;
    esac
}

show_help "${1:-}"
