/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResendVerificationRouteImport } from './routes/resend-verification'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AccountRouteImport } from './routes/account'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as ContactsNewRouteImport } from './routes/contacts/new'
import { Route as ContactsMergeRouteImport } from './routes/contacts/merge'
import { Route as ContactsImportRouteImport } from './routes/contacts/import'
import { Route as ContactsAddressBookIdRouteImport } from './routes/contacts/$addressBookId'
import { Route as GroupsGroupIdAcceptInvitationRouteImport } from './routes/groups/$groupId/accept-invitation'
import { Route as ContactsGroupsGroupIdRouteImport } from './routes/contacts/groups/$groupId'
import { Route as ContactsAddressBookIdContactsNewRouteImport } from './routes/contacts/$addressBookId/contacts/new'
import { Route as ContactsAddressBookIdContactsContactIdRouteImport } from './routes/contacts/$addressBookId/contacts/$contactId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResendVerificationRoute = ResendVerificationRouteImport.update({
  id: '/resend-verification',
  path: '/resend-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/edit-profile.lazy').then((d) => d.Route))
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/delete-account.lazy').then((d) => d.Route),
)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/change-password.lazy').then((d) => d.Route),
)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/account.lazy').then((d) => d.Route))
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactsRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/share/$token.lazy').then((d) => d.Route))
const ContactsNewRoute = ContactsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ContactsRoute,
} as any)
const ContactsMergeRoute = ContactsMergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => ContactsRoute,
} as any).lazy(() =>
  import('./routes/contacts/merge.lazy').then((d) => d.Route),
)
const ContactsImportRoute = ContactsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ContactsRoute,
} as any).lazy(() =>
  import('./routes/contacts/import.lazy').then((d) => d.Route),
)
const ContactsAddressBookIdRoute = ContactsAddressBookIdRouteImport.update({
  id: '/$addressBookId',
  path: '/$addressBookId',
  getParentRoute: () => ContactsRoute,
} as any).lazy(() =>
  import('./routes/contacts/$addressBookId.lazy').then((d) => d.Route),
)
const GroupsGroupIdAcceptInvitationRoute =
  GroupsGroupIdAcceptInvitationRouteImport.update({
    id: '/groups/$groupId/accept-invitation',
    path: '/groups/$groupId/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactsGroupsGroupIdRoute = ContactsGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => ContactsRoute,
} as any).lazy(() =>
  import('./routes/contacts/groups/$groupId.lazy').then((d) => d.Route),
)
const ContactsAddressBookIdContactsNewRoute =
  ContactsAddressBookIdContactsNewRouteImport.update({
    id: '/contacts/new',
    path: '/contacts/new',
    getParentRoute: () => ContactsAddressBookIdRoute,
  } as any)
const ContactsAddressBookIdContactsContactIdRoute =
  ContactsAddressBookIdContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => ContactsAddressBookIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/account': typeof AccountRoute
  '/change-password': typeof ChangePasswordRoute
  '/check-email': typeof CheckEmailRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/edit-profile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/contacts/$addressBookId': typeof ContactsAddressBookIdRouteWithChildren
  '/contacts/import': typeof ContactsImportRoute
  '/contacts/merge': typeof ContactsMergeRoute
  '/contacts/new': typeof ContactsNewRoute
  '/share/$token': typeof ShareTokenRoute
  '/contacts/': typeof ContactsIndexRoute
  '/contacts/groups/$groupId': typeof ContactsGroupsGroupIdRoute
  '/groups/$groupId/accept-invitation': typeof GroupsGroupIdAcceptInvitationRoute
  '/contacts/$addressBookId/contacts/$contactId': typeof ContactsAddressBookIdContactsContactIdRoute
  '/contacts/$addressBookId/contacts/new': typeof ContactsAddressBookIdContactsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/account': typeof AccountRoute
  '/change-password': typeof ChangePasswordRoute
  '/check-email': typeof CheckEmailRoute
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/edit-profile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/contacts/$addressBookId': typeof ContactsAddressBookIdRouteWithChildren
  '/contacts/import': typeof ContactsImportRoute
  '/contacts/merge': typeof ContactsMergeRoute
  '/contacts/new': typeof ContactsNewRoute
  '/share/$token': typeof ShareTokenRoute
  '/contacts': typeof ContactsIndexRoute
  '/contacts/groups/$groupId': typeof ContactsGroupsGroupIdRoute
  '/groups/$groupId/accept-invitation': typeof GroupsGroupIdAcceptInvitationRoute
  '/contacts/$addressBookId/contacts/$contactId': typeof ContactsAddressBookIdContactsContactIdRoute
  '/contacts/$addressBookId/contacts/new': typeof ContactsAddressBookIdContactsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/account': typeof AccountRoute
  '/change-password': typeof ChangePasswordRoute
  '/check-email': typeof CheckEmailRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/edit-profile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/contacts/$addressBookId': typeof ContactsAddressBookIdRouteWithChildren
  '/contacts/import': typeof ContactsImportRoute
  '/contacts/merge': typeof ContactsMergeRoute
  '/contacts/new': typeof ContactsNewRoute
  '/share/$token': typeof ShareTokenRoute
  '/contacts/': typeof ContactsIndexRoute
  '/contacts/groups/$groupId': typeof ContactsGroupsGroupIdRoute
  '/groups/$groupId/accept-invitation': typeof GroupsGroupIdAcceptInvitationRoute
  '/contacts/$addressBookId/contacts/$contactId': typeof ContactsAddressBookIdContactsContactIdRoute
  '/contacts/$addressBookId/contacts/new': typeof ContactsAddressBookIdContactsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/account'
    | '/change-password'
    | '/check-email'
    | '/contacts'
    | '/dashboard'
    | '/delete-account'
    | '/edit-profile'
    | '/forgot-password'
    | '/login'
    | '/resend-verification'
    | '/reset-password'
    | '/verify-email'
    | '/contacts/$addressBookId'
    | '/contacts/import'
    | '/contacts/merge'
    | '/contacts/new'
    | '/share/$token'
    | '/contacts/'
    | '/contacts/groups/$groupId'
    | '/groups/$groupId/accept-invitation'
    | '/contacts/$addressBookId/contacts/$contactId'
    | '/contacts/$addressBookId/contacts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/account'
    | '/change-password'
    | '/check-email'
    | '/dashboard'
    | '/delete-account'
    | '/edit-profile'
    | '/forgot-password'
    | '/login'
    | '/resend-verification'
    | '/reset-password'
    | '/verify-email'
    | '/contacts/$addressBookId'
    | '/contacts/import'
    | '/contacts/merge'
    | '/contacts/new'
    | '/share/$token'
    | '/contacts'
    | '/contacts/groups/$groupId'
    | '/groups/$groupId/accept-invitation'
    | '/contacts/$addressBookId/contacts/$contactId'
    | '/contacts/$addressBookId/contacts/new'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/account'
    | '/change-password'
    | '/check-email'
    | '/contacts'
    | '/dashboard'
    | '/delete-account'
    | '/edit-profile'
    | '/forgot-password'
    | '/login'
    | '/resend-verification'
    | '/reset-password'
    | '/verify-email'
    | '/contacts/$addressBookId'
    | '/contacts/import'
    | '/contacts/merge'
    | '/contacts/new'
    | '/share/$token'
    | '/contacts/'
    | '/contacts/groups/$groupId'
    | '/groups/$groupId/accept-invitation'
    | '/contacts/$addressBookId/contacts/$contactId'
    | '/contacts/$addressBookId/contacts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AccountRoute: typeof AccountRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CheckEmailRoute: typeof CheckEmailRoute
  ContactsRoute: typeof ContactsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  EditProfileRoute: typeof EditProfileRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResendVerificationRoute: typeof ResendVerificationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ShareTokenRoute: typeof ShareTokenRoute
  GroupsGroupIdAcceptInvitationRoute: typeof GroupsGroupIdAcceptInvitationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resend-verification': {
      id: '/resend-verification'
      path: '/resend-verification'
      fullPath: '/resend-verification'
      preLoaderRoute: typeof ResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/new': {
      id: '/contacts/new'
      path: '/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof ContactsNewRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/contacts/merge': {
      id: '/contacts/merge'
      path: '/merge'
      fullPath: '/contacts/merge'
      preLoaderRoute: typeof ContactsMergeRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/contacts/import': {
      id: '/contacts/import'
      path: '/import'
      fullPath: '/contacts/import'
      preLoaderRoute: typeof ContactsImportRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/contacts/$addressBookId': {
      id: '/contacts/$addressBookId'
      path: '/$addressBookId'
      fullPath: '/contacts/$addressBookId'
      preLoaderRoute: typeof ContactsAddressBookIdRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/groups/$groupId/accept-invitation': {
      id: '/groups/$groupId/accept-invitation'
      path: '/groups/$groupId/accept-invitation'
      fullPath: '/groups/$groupId/accept-invitation'
      preLoaderRoute: typeof GroupsGroupIdAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/groups/$groupId': {
      id: '/contacts/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/contacts/groups/$groupId'
      preLoaderRoute: typeof ContactsGroupsGroupIdRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/contacts/$addressBookId/contacts/new': {
      id: '/contacts/$addressBookId/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/$addressBookId/contacts/new'
      preLoaderRoute: typeof ContactsAddressBookIdContactsNewRouteImport
      parentRoute: typeof ContactsAddressBookIdRoute
    }
    '/contacts/$addressBookId/contacts/$contactId': {
      id: '/contacts/$addressBookId/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$addressBookId/contacts/$contactId'
      preLoaderRoute: typeof ContactsAddressBookIdContactsContactIdRouteImport
      parentRoute: typeof ContactsAddressBookIdRoute
    }
  }
}

interface ContactsAddressBookIdRouteChildren {
  ContactsAddressBookIdContactsContactIdRoute: typeof ContactsAddressBookIdContactsContactIdRoute
  ContactsAddressBookIdContactsNewRoute: typeof ContactsAddressBookIdContactsNewRoute
}

const ContactsAddressBookIdRouteChildren: ContactsAddressBookIdRouteChildren = {
  ContactsAddressBookIdContactsContactIdRoute:
    ContactsAddressBookIdContactsContactIdRoute,
  ContactsAddressBookIdContactsNewRoute: ContactsAddressBookIdContactsNewRoute,
}

const ContactsAddressBookIdRouteWithChildren =
  ContactsAddressBookIdRoute._addFileChildren(
    ContactsAddressBookIdRouteChildren,
  )

interface ContactsRouteChildren {
  ContactsAddressBookIdRoute: typeof ContactsAddressBookIdRouteWithChildren
  ContactsImportRoute: typeof ContactsImportRoute
  ContactsMergeRoute: typeof ContactsMergeRoute
  ContactsNewRoute: typeof ContactsNewRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  ContactsGroupsGroupIdRoute: typeof ContactsGroupsGroupIdRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsAddressBookIdRoute: ContactsAddressBookIdRouteWithChildren,
  ContactsImportRoute: ContactsImportRoute,
  ContactsMergeRoute: ContactsMergeRoute,
  ContactsNewRoute: ContactsNewRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  ContactsGroupsGroupIdRoute: ContactsGroupsGroupIdRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AccountRoute: AccountRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CheckEmailRoute: CheckEmailRoute,
  ContactsRoute: ContactsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  EditProfileRoute: EditProfileRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResendVerificationRoute: ResendVerificationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ShareTokenRoute: ShareTokenRoute,
  GroupsGroupIdAcceptInvitationRoute: GroupsGroupIdAcceptInvitationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
