/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResendVerificationRouteImport } from './routes/resend-verification'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AccountRouteImport } from './routes/account'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TasksNewRouteImport } from './routes/tasks/new'
import { Route as TasksMergeRouteImport } from './routes/tasks/merge'
import { Route as TasksImportRouteImport } from './routes/tasks/import'
import { Route as TasksTaskListIdRouteImport } from './routes/tasks/$taskListId'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as TasksGroupsGroupIdRouteImport } from './routes/tasks/groups/$groupId'
import { Route as GroupsGroupIdAcceptInvitationRouteImport } from './routes/groups/$groupId/accept-invitation'
import { Route as TasksTaskListIdTasksNewRouteImport } from './routes/tasks/$taskListId/tasks/new'
import { Route as TasksTaskListIdTasksTaskIdRouteImport } from './routes/tasks/$taskListId/tasks/$taskId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResendVerificationRoute = ResendVerificationRouteImport.update({
  id: '/resend-verification',
  path: '/resend-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TasksRoute,
} as any)
const TasksMergeRoute = TasksMergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => TasksRoute,
} as any)
const TasksImportRoute = TasksImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskListIdRoute = TasksTaskListIdRouteImport.update({
  id: '/$taskListId',
  path: '/$taskListId',
  getParentRoute: () => TasksRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksGroupsGroupIdRoute = TasksGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => TasksRoute,
} as any)
const GroupsGroupIdAcceptInvitationRoute =
  GroupsGroupIdAcceptInvitationRouteImport.update({
    id: '/groups/$groupId/accept-invitation',
    path: '/groups/$groupId/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const TasksTaskListIdTasksNewRoute = TasksTaskListIdTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => TasksTaskListIdRoute,
} as any)
const TasksTaskListIdTasksTaskIdRoute =
  TasksTaskListIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => TasksTaskListIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/account': typeof AccountRoute
  '/change-password': typeof ChangePasswordRoute
  '/check-email': typeof CheckEmailRoute
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/edit-profile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tasks': typeof TasksRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/share/$token': typeof ShareTokenRoute
  '/tasks/$taskListId': typeof TasksTaskListIdRouteWithChildren
  '/tasks/import': typeof TasksImportRoute
  '/tasks/merge': typeof TasksMergeRoute
  '/tasks/new': typeof TasksNewRoute
  '/tasks/': typeof TasksIndexRoute
  '/groups/$groupId/accept-invitation': typeof GroupsGroupIdAcceptInvitationRoute
  '/tasks/groups/$groupId': typeof TasksGroupsGroupIdRoute
  '/tasks/$taskListId/tasks/$taskId': typeof TasksTaskListIdTasksTaskIdRoute
  '/tasks/$taskListId/tasks/new': typeof TasksTaskListIdTasksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/account': typeof AccountRoute
  '/change-password': typeof ChangePasswordRoute
  '/check-email': typeof CheckEmailRoute
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/edit-profile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/share/$token': typeof ShareTokenRoute
  '/tasks/$taskListId': typeof TasksTaskListIdRouteWithChildren
  '/tasks/import': typeof TasksImportRoute
  '/tasks/merge': typeof TasksMergeRoute
  '/tasks/new': typeof TasksNewRoute
  '/tasks': typeof TasksIndexRoute
  '/groups/$groupId/accept-invitation': typeof GroupsGroupIdAcceptInvitationRoute
  '/tasks/groups/$groupId': typeof TasksGroupsGroupIdRoute
  '/tasks/$taskListId/tasks/$taskId': typeof TasksTaskListIdTasksTaskIdRoute
  '/tasks/$taskListId/tasks/new': typeof TasksTaskListIdTasksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/account': typeof AccountRoute
  '/change-password': typeof ChangePasswordRoute
  '/check-email': typeof CheckEmailRoute
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/edit-profile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tasks': typeof TasksRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/share/$token': typeof ShareTokenRoute
  '/tasks/$taskListId': typeof TasksTaskListIdRouteWithChildren
  '/tasks/import': typeof TasksImportRoute
  '/tasks/merge': typeof TasksMergeRoute
  '/tasks/new': typeof TasksNewRoute
  '/tasks/': typeof TasksIndexRoute
  '/groups/$groupId/accept-invitation': typeof GroupsGroupIdAcceptInvitationRoute
  '/tasks/groups/$groupId': typeof TasksGroupsGroupIdRoute
  '/tasks/$taskListId/tasks/$taskId': typeof TasksTaskListIdTasksTaskIdRoute
  '/tasks/$taskListId/tasks/new': typeof TasksTaskListIdTasksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/account'
    | '/change-password'
    | '/check-email'
    | '/dashboard'
    | '/delete-account'
    | '/edit-profile'
    | '/forgot-password'
    | '/login'
    | '/resend-verification'
    | '/reset-password'
    | '/tasks'
    | '/verify-email'
    | '/share/$token'
    | '/tasks/$taskListId'
    | '/tasks/import'
    | '/tasks/merge'
    | '/tasks/new'
    | '/tasks/'
    | '/groups/$groupId/accept-invitation'
    | '/tasks/groups/$groupId'
    | '/tasks/$taskListId/tasks/$taskId'
    | '/tasks/$taskListId/tasks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/account'
    | '/change-password'
    | '/check-email'
    | '/dashboard'
    | '/delete-account'
    | '/edit-profile'
    | '/forgot-password'
    | '/login'
    | '/resend-verification'
    | '/reset-password'
    | '/verify-email'
    | '/share/$token'
    | '/tasks/$taskListId'
    | '/tasks/import'
    | '/tasks/merge'
    | '/tasks/new'
    | '/tasks'
    | '/groups/$groupId/accept-invitation'
    | '/tasks/groups/$groupId'
    | '/tasks/$taskListId/tasks/$taskId'
    | '/tasks/$taskListId/tasks/new'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/account'
    | '/change-password'
    | '/check-email'
    | '/dashboard'
    | '/delete-account'
    | '/edit-profile'
    | '/forgot-password'
    | '/login'
    | '/resend-verification'
    | '/reset-password'
    | '/tasks'
    | '/verify-email'
    | '/share/$token'
    | '/tasks/$taskListId'
    | '/tasks/import'
    | '/tasks/merge'
    | '/tasks/new'
    | '/tasks/'
    | '/groups/$groupId/accept-invitation'
    | '/tasks/groups/$groupId'
    | '/tasks/$taskListId/tasks/$taskId'
    | '/tasks/$taskListId/tasks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AccountRoute: typeof AccountRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CheckEmailRoute: typeof CheckEmailRoute
  DashboardRoute: typeof DashboardRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  EditProfileRoute: typeof EditProfileRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResendVerificationRoute: typeof ResendVerificationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TasksRoute: typeof TasksRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  ShareTokenRoute: typeof ShareTokenRoute
  GroupsGroupIdAcceptInvitationRoute: typeof GroupsGroupIdAcceptInvitationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resend-verification': {
      id: '/resend-verification'
      path: '/resend-verification'
      fullPath: '/resend-verification'
      preLoaderRoute: typeof ResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/merge': {
      id: '/tasks/merge'
      path: '/merge'
      fullPath: '/tasks/merge'
      preLoaderRoute: typeof TasksMergeRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/import': {
      id: '/tasks/import'
      path: '/import'
      fullPath: '/tasks/import'
      preLoaderRoute: typeof TasksImportRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskListId': {
      id: '/tasks/$taskListId'
      path: '/$taskListId'
      fullPath: '/tasks/$taskListId'
      preLoaderRoute: typeof TasksTaskListIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/groups/$groupId': {
      id: '/tasks/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/tasks/groups/$groupId'
      preLoaderRoute: typeof TasksGroupsGroupIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/groups/$groupId/accept-invitation': {
      id: '/groups/$groupId/accept-invitation'
      path: '/groups/$groupId/accept-invitation'
      fullPath: '/groups/$groupId/accept-invitation'
      preLoaderRoute: typeof GroupsGroupIdAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskListId/tasks/new': {
      id: '/tasks/$taskListId/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/$taskListId/tasks/new'
      preLoaderRoute: typeof TasksTaskListIdTasksNewRouteImport
      parentRoute: typeof TasksTaskListIdRoute
    }
    '/tasks/$taskListId/tasks/$taskId': {
      id: '/tasks/$taskListId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskListId/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskListIdTasksTaskIdRouteImport
      parentRoute: typeof TasksTaskListIdRoute
    }
  }
}

interface TasksTaskListIdRouteChildren {
  TasksTaskListIdTasksTaskIdRoute: typeof TasksTaskListIdTasksTaskIdRoute
  TasksTaskListIdTasksNewRoute: typeof TasksTaskListIdTasksNewRoute
}

const TasksTaskListIdRouteChildren: TasksTaskListIdRouteChildren = {
  TasksTaskListIdTasksTaskIdRoute: TasksTaskListIdTasksTaskIdRoute,
  TasksTaskListIdTasksNewRoute: TasksTaskListIdTasksNewRoute,
}

const TasksTaskListIdRouteWithChildren = TasksTaskListIdRoute._addFileChildren(
  TasksTaskListIdRouteChildren,
)

interface TasksRouteChildren {
  TasksTaskListIdRoute: typeof TasksTaskListIdRouteWithChildren
  TasksImportRoute: typeof TasksImportRoute
  TasksMergeRoute: typeof TasksMergeRoute
  TasksNewRoute: typeof TasksNewRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TasksGroupsGroupIdRoute: typeof TasksGroupsGroupIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskListIdRoute: TasksTaskListIdRouteWithChildren,
  TasksImportRoute: TasksImportRoute,
  TasksMergeRoute: TasksMergeRoute,
  TasksNewRoute: TasksNewRoute,
  TasksIndexRoute: TasksIndexRoute,
  TasksGroupsGroupIdRoute: TasksGroupsGroupIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AccountRoute: AccountRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CheckEmailRoute: CheckEmailRoute,
  DashboardRoute: DashboardRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  EditProfileRoute: EditProfileRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResendVerificationRoute: ResendVerificationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TasksRoute: TasksRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  ShareTokenRoute: ShareTokenRoute,
  GroupsGroupIdAcceptInvitationRoute: GroupsGroupIdAcceptInvitationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
